### ISSUE TITLE
IndexOutOfRangeException on .Build() for certain Chinese input

### ISSUE THREAD

**Issue by darklajid** [nreco/AhoCorasickDoubleArrayTrie#4]
Let's just not go into why I have this dataset .. :-/

Given a dictionary of 5000 Chinese strings/needles (I cannot read Chinese myself), .Build() throws an IndexOutOfRangeException for me. 

I could reduce ONE failure to the following:

    var lines = new[]
    {
        "苏尔寿工艺泵（美国）有限公司",
        "苏尔寿（德国）有限公司",
        "苏尔寿栗苏州"
    };
    var trie = new AhoCorasickDoubleArrayTrie<string>();
    trie.Build(lines.ToDictionary(x => x), true); // throws

1) In this particular scenario it seems to be related to the fullwidth left/right parenthesis characters in the input (i.e. removing them "solves" the issue), but neither can I remove them from my actual dataset (not under my control) nor are these the only issues (if I remove these characters from the 3 lines sample, everything works. If I remove these characters from my 5000 lines of input, it still crashes in Build(). Not sure if the characters are a red herring)

2) The initial exception is thrown in `NReco.Text.AhoCorasickDoubleArrayTrie`1.Builder.insert()`, line 245. `begin + siblings[i].Key` is outside the range of `trie.check`.

I could fix this exception by going through the sources and note this line in `buildDoubleArrayTrie()`:

    resize(65536 + totalKeysLen*2 + 1);  // originally was 65536*32  -- it seems too large in most cases

It seems in my case .. the change from Java isn't large enough? If I change this back to

    resize(65536*32);

I can pass the code throwing the error above. Unfortunately I run into the next IndexOutOfRangeException in `NReco.Text.AhoCorasickDoubleArrayTrie`1.State.SetFailure()`, line 85. `fail[index]` tries to access index 74743 in a 65311 sized array for me.

I'll try to look into this myself, but would love your input:
* Is the resize() change sound or was that an optimization?
* Any idea why the SetFailure() call throws now?

FWIW: Cloning the Java implementation and testing the very same code/three lines of input successfully builds a trie.

**Comment by darklajid** [comment]
Thanks for merging the fix. If you would consider bumping the version (with or without the `Save(stream, false)` PR), that would be awesome. For now I'm on a local fork for these Chinese character issues, but I'd love to switch back to Nuget instead.

**Comment by VitaliyMF** [comment]
@darklajid no problems with your PR #6 (thank you for the contribution!) however I want to add an overload that accepts handler to resolve values too. I'm a bit busy these days; I'll try to publish new lib version on nuget.org as soon as possible (hope on this week).

**Comment by VitaliyMF** [comment]
Shipped in 1.0.2
